#!/bin/bash

# 20分钟紧急任务广播通知

echo "📢 团队广播：20分钟产品经理紧急任务"
echo "=============================================="
echo ""
echo "📅 广播时间: $(date)"
echo "🎯 主题: 产品经理20分钟紧急执行任务"
echo "🔴 紧急程度: 最高优先级"
echo ""
echo "📋 任务信息:"
echo "产品经理Alex需要在20分钟内完成所有积压的产品工作"
echo "开始时间: 03:00"
echo "截止时间: 03:20"
echo "总时长: 20分钟"
echo "任务数量: 15项"
echo ""
echo "🎯 执行目标:"
echo "1. 处理所有待处理的需求"
echo "2. 完善所有文档产出"
echo "3. 更新项目状态"
echo "4. 准备下一步行动"
echo ""
echo "📊 具体任务:"
echo "1. 需求处理 (8分钟)"
echo "   • 本地行情数据库需求"
echo "   • 行情切换和信号验证需求"
echo "   • 综合需求决策"
echo ""
echo "2. 文档完善 (7分钟)"
echo "   • 需求调研报告完善"
echo "   • PRD文档完善"
echo "   • 业务流程图完善"
echo "   • 产品原型图完善"
echo "   • 产品路线图制定"
echo ""
echo "3. 项目更新 (3分钟)"
echo "   • 项目看板更新"
echo "   • 进度报告更新"
echo "   • 下一步行动准备"
echo ""
echo "4. 沟通协调 (2分钟)"
echo "   • 团队通知"
echo "   • 会议材料准备"
echo ""
echo "🛠️ 执行工具:"
echo "• 执行计划: ./20分钟产品经理紧急执行计划.md"
echo "• 监控脚本: ./20min_product_urgent.sh"
echo "• 紧急指令: ./collaboration/push_messages/product_20min_urgent.txt"
echo ""
echo "⏰ 时间监控:"
echo "• 开始时间: 03:00"
echo "• 5分钟检查点: 03:05"
echo "• 10分钟检查点: 03:10"
echo "• 15分钟检查点: 03:15"
echo "• 完成时间: 03:20"
echo ""
echo "📈 预期影响:"
echo "✅ 项目可以继续推进"
echo "✅ 技术团队可以开始开发"
echo "✅ 风险得到有效控制"
echo "✅ 质量达到可用标准"
echo ""
echo "🤝 团队协作要求:"
echo "1. 技术团队: 准备接收需求决策，开始技术方案设计"
echo "2. 运营团队: 准备接收产品方向，调整运营计划"
echo "3. 测试团队: 准备接收测试重点，开始测试计划"
echo "4. 所有团队: 保持通信畅通，随时准备支持"
echo ""
echo "🚨 紧急支持通道:"
echo "• 技术咨询: 技术团队Slack频道"
echo "• 业务咨询: 运营团队Slack频道"
echo "• 质量咨询: 测试团队Slack频道"
echo "• 紧急联系: 项目协调系统"
echo ""
echo "📊 历史参考:"
echo "上次30分钟紧急任务提前3分30秒完成"
echo "展示了产品经理卓越的执行能力"
echo "本次20分钟任务更具挑战性"
echo "但相信能够再次出色完成"
echo ""
echo "🎯 成功标准:"
echo "✅ 20分钟内完成所有15项任务"
echo "✅ 所有需求得到处理"
echo "✅ 所有文档基本完善"
echo "✅ 项目状态准确更新"
echo "✅ 团队明确下一步行动"
echo ""
echo "📱 监控系统:"
echo "• 20分钟倒计时监控已启动"
echo "• 任务完成状态实时记录"
echo "• 执行报告自动生成"
echo "• 完成通知自动发送"
echo ""
echo "📍 相关文档:"
echo "• 项目看板: ./collaboration/shared/quant_project_board.md"
echo "• 执行计划: ./20分钟产品经理紧急执行计划.md"
echo "• 监控目录: ./collaboration/20min_monitor/"
echo "• 需求文档: ./本地行情数据库需求提案.md"
echo "• 需求文档: ./行情切换和信号验证需求提案.md"
echo ""
echo "🎉 成功后的行动:"
echo "1. 立即组织需求评审会议"
echo "2. 协调技术团队开始开发"
echo "3. 准备项目周会材料"
echo "4. 监控执行效果"
echo ""
echo "🏆 团队支持:"
echo "请所有团队给予产品经理全力支持"
echo "保持通信畅通，随时准备协助"
echo "共同确保20分钟任务成功完成"
echo ""
echo "=============================================="
echo "🚀 20分钟紧急任务已启动！"
echo "请所有团队做好准备，03:20后立即行动！"
echo ""
echo "📢 广播结束"
echo "下次更新: 03:20任务完成后"